# Generated by Django 3.2.15 on 2022-08-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_policyUseChoice', models.CharField(max_length=50, null=True)),
                ('construction', models.BooleanField(null=True)),
                ('finance', models.BooleanField(null=True)),
                ('employment', models.BooleanField(null=True)),
                ('freelancer', models.BooleanField(null=True)),
                ('health_care', models.BooleanField(null=True)),
                ('saas', models.BooleanField(null=True)),
                ('entertainment', models.BooleanField(null=True)),
                ('real_estate', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_c_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Terms_and_condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('tnc_or_policy', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 't_C',
            },
        ),
    ]
